### ISSUE TITLE
Space above removed header

### ISSUE THREAD

**Issue by edwardvuong** [mattsouza26/sticky_az_list#1]
When setting the `showSectionHeader` to `false`, there is still some padding above the header in the list view.

```
StickyAzOptions(
     listOptions: ListOptions(
     showSectionHeader: false,
),
```

![image](https://github.com/mattsouza26/sticky_az_list/assets/11309479/f0c9d877-fb4f-45df-b495-cd36dd5d7d97)

![](https://user-images.githubusercontent.com/74125222/236589280-019529f1-c730-499f-a681-66d00cbee439.gif)
This differs from the demo where when the header is hidden, there is no spacing between each A-Z group.

**Comment by mattsouza26** [comment]
i tried set to false the showSectionHeader and doesn't show any padding on that, so consider to send the full code of yours so i can help u detect the issue

**Comment by mattsouza26** [comment]
this was a problem only on IOS and now it was fixed.
