### ISSUE TITLE
NestedScroll not working on iOS 

### ISSUE THREAD

**Issue by w-peterson** [mattsouza26/sticky_az_list#2]
The NestedScroll example doesn't scroll down properly on iOS simulators or devices.

**Comment by mattsouza26** [comment]
> The NestedScroll example doesn't scroll down properly on iOS simulators or devices.

give more details about this with code and video

**Comment by w-peterson** [comment]
Hi Matt, I used your source code example, and I clicked the NestedScroll button. If I scroll the list up, the image disappears properly. If I scroll the list down, it will not show the entire image. Please see the video.

https://github.com/mattsouza26/sticky_az_list/assets/140921848/de2f537c-0daa-43a1-bcd8-2bf548abc5eb

I do have a work around by changing the NestedScrollControllerPhysics to extend from ClampingScrollPhysics instead of ScrollPhysics.

**Comment by mattsouza26** [comment]
> Hi Matt, I used your source code example, and I clicked the NestedScroll button. If I scroll the list up, the image disappears properly. If I scroll the list down, it will not show the entire image. Please see the video.
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2023-11-18.at.16.26.04.mp4 
> I do have a work around by changing the NestedScrollControllerPhysics to extend from ClampingScrollPhysics instead of ScrollPhysics.

this is the default scrolling in ios, I didn't want to change this, so you can use the parent parameter of NestedScrollControllerPhysics and use ClampingScrollPhysics or you can do what it says and extend ClampingScrollPhysics directly.
